# Security Audit Report: VM Host Critical Resource Management Vulnerabilities

**Report ID:** MX-VM-V1.4-AUDIT-001  
**Project:** `mx-chain-vm-v1_4-go`  
**Status:** DRAFT / PENDING REMEDIATION  
**Severity:** CRITICAL / HIGH  

---

## 1. Executive Summary

This report documents two critical security vulnerabilities identified during a targeted audit of the WebAssembly (WASM) Virtual Machine host implementation. These vulnerabilities reside in the host-hook layer (EEI) and specifically target resource management flaws that can be exploited to crash validator nodes or halt the network.

Unlike logic errors, these are **Resource Exhaustion (DoS)** vectors that bypass the VM's gas-metering safety net.

---

## 2. Vulnerability Details

### 2.1 [REAL-4] Unbounded BigInt Shift Left (Host OOM)

| Attribute | Details |
| :--- | :--- |
| **Severity** | **CRITICAL** |
| **Location** | `vmhost/vmhooks/bigIntOps.go:v1_4_bigIntShl` |
| **Impact** | Host Process Termination (OOM) |
| **Fix Safety** | **HIGH** (Safe to implement without breaking consensus) |

#### Technical Analysis
The `v1_4_bigIntShl` hook exports the BigInt shift-left operation to the WASM guest. It accepts an `int32` value for the number of bits to shift.

```go
// Location: vmhost/vmhooks/bigIntOps.go
func v1_4_bigIntShl(context unsafe.Pointer, destinationHandle, opHandle int32, bits int32) {
    // ... gas charged for base op ...
    dest.Lsh(a, uint(bits)) // <--- VULNERABILITY: Unbounded allocation
    managedType.ConsumeGasForBigIntCopy(dest)
}
```

If a contract provides a `bits` value of `2,147,483,647` (MaxInt32), the `math/big` library will attempt to allocate a buffer large enough to hold **2 billion bits (~256 MB)**. 

#### Exploit Scenario
An attacker can repeatedly call `bigIntShl` with a large `bits` parameter. Because the gas for the resulting size is only charged **after** the allocation and computation are complete, the node will crash due to an Out-of-Memory (OOM) error before it can ever penalize the attacker's gas balance.

---

### 2.2 [REAL-6] Unmetered Large Memory Allocation (OOM/DoS)

| Attribute | Details |
| :--- | :--- |
| **Severity** | **HIGH** |
| **Location** | `vmhost/vmhooks/baseOps.go:getArgumentsFromMemory` |
| **Impact** | Host Memory Exhaustion / CPU Spike |
| **Fix Safety** | **HIGH** (Safe to implement without breaking consensus) |

#### Technical Analysis
The `getArgumentsFromMemory` helper is used by core EEI functions (e.g., `transferValueExecute`) to load complex argument arrays from WASM linear memory into the host.

```go
// Location: vmhost/vmhooks/baseOps.go
func getArgumentsFromMemory(host vmhost.VMHost, numArguments int32, ...) {
    // ...
    argumentsLengthData, err := runtime.MemLoad(argumentsLengthOffset, numArguments*4) // <--- Unmetered Copy
    // ...
    data, err := runtime.MemLoadMultiple(dataOffset, argumentLengths) // <--- Unmetered Copies
    // ...
    return data, totalArgumentBytes, nil
}
```

The function performs multiple `MemLoad` operations. In the current architecture, `MemLoad` allocates a fresh Go slice and copies data from Wasmer memory but **does not deduct gas internally**. The gas is deducted in the calling function **only after** `getArgumentsFromMemory` returns.

#### Exploit Scenario
An attacker can specify `numArguments` as a very large value (e.g., $10^6$). The host will immediately allocate and copy 4MB of metadata, followed by potentially hundreds of megabytes of argument data. If the total size exceeds available host RAM, the node crashes. Since no gas was deducted *during* the loading phase, the attacker pays nothing for the crash.

---

## 3. Remediation Strategy

### 3.1 Remediation for REAL-4
Implement a hard cap on the `bits` parameter and perform "Pre-emptive Gas Charging."
1.  Validate that `bits` does not exceed a reasonable threshold (e.g., 1,000,000 bits).
2.  Calculate the final bit-length of the result ($originalBits + shiftAmount$) and deduct the `CopyPerByteForTooBig` gas **before** calling `dest.Lsh`.

### 3.2 Remediation for REAL-6
Implement "Gas-First" loading in `getArgumentsFromMemory`.
1.  Deduct gas for the `numArguments * 4` metadata load *before* calling `MemLoad`.
2.  In the loop that loads arguments, maintain a running sum of `totalBytes` and deduct gas incrementally *before* each `MemLoad` call.
3.  If gas is exhausted, return an error immediately without performing further allocations.

---

## 4. Conclusion

Both **REAL-4** and **REAL-6** represent "Safe-to-Fix" vulnerabilities. Implementing the suggested remediations will significantly harden the validator nodes against memory-based DoS attacks without impacting the deterministic outcome of smart contracts or requiring a breaking change to the gas schedule logic.

---
*Generated by Antigravity Security Audit Suite*
